### ISSUE TITLE
قرار دادن کانفیگ خودمان

### ISSUE THREAD

**Issue by ailabm2246** [goingfine/WinCFScan#11]
سلام اگه بخوایم توی real.config کانفیگ خودمون رو قرار بدیم پارامترهای serverName و Host با توجه به کانفیگ های vmess در نرم افزار v2rayn میشه comouflage domain و SNI  درسته؟
و یه نکته دیگه اینکه موقع شروع نرم افزار این پیغام رو میده :
Fronting domain is not accesible! you might need to get new frontig url from our github or check your internet connection.
 چطور میشه رفعش کرد؟ یعنی اصلا این Fronting domain چیه  و چطور میشه عوضش کرد؟

**Comment by goingfine** [comment]
آخرین نسخه رو دانلود کنید مشکل فرانتینگ حل شده
ضمنا از این به بعد توی ریپوی مرتضی ادامه خواهیم داد
