### ISSUE TITLE
تعداد ترد ها

### ISSUE THREAD

**Issue by megasoheilsh** [goingfine/WinCFScan#4]
سلام تعداد concurrect ها یا همان ترد 16 عدد کمه اگر امکانش هست محدودیتش رو بردارید با تشکر

**Comment by raminrez** [comment]
من هم به این امکان نیاز دارم
اینکه گزینه ۳۲ ۶۴ هم اضافه کنید خیلی خوبه

**Comment by megasoheilsh** [comment]
> 

باز هم کمه ، تو پارالل لینوکسی خود اقا مرتضی محدودیت تا 248 بود ولی ویندوز دیگه محدودیت نداره میشه بی نهایت ترد گذاشت

**Comment by goingfine** [comment]
اینجا میتونید عوضش کنید بعد بیلد کنید
https://github.com/goingfine/WinCFScan/blob/main/frmMain.cs#L359

**Comment by megasoheilsh** [comment]
> اینجا میتونید عوضش کنید بعد بیلد کنید https://github.com/goingfine/WinCFScan/blob/main/frmMain.cs#L359


 مهندس جان اگر زحمتشو بکشی ممنون میشیم ، ما دو ساعتی باید بریم دنبال نصب ویژال استدیو. ضما امکانش هست ایدی تلگرام بدید؟

**Comment by goingfine** [comment]
باشه تو ریلیز بعدی تغییرش میدیم

**Comment by megasoheilsh** [comment]
> باشه تو ریلیز بعدی تغییرش میدیم

ممنون. فقط محدود نباشه

**Comment by megasoheilsh** [comment]
> باشه تو ریلیز بعدی تغییرش میدیم

در ایپدیتی که چند ساعت پیش گذاشتید همچنان ماکسیمم 16 می باشد !

**Comment by yusefes** [comment]
> 

در این آپدیت مشکل دومین رو برطرف کردن.

**Comment by goingfine** [comment]
> > باشه تو ریلیز بعدی تغییرش میدیم
> 
> در ایپدیتی که چند ساعت پیش گذاشتید همچنان ماکسیمم 16 می باشد !

عرض کردم تو ریلیز بعدی.
ضمنا بچه ها ریلیز های بعدی رو توی ریپوی مرتضی ادامه میدیم. اونجا رو هم چک کنید

**Comment by megasoheilsh** [comment]
> > > باشه تو ریلیز بعدی تغییرش میدیم
> > 
> > 
> > در ایپدیتی که چند ساعت پیش گذاشتید همچنان ماکسیمم 16 می باشد !
> 
> عرض کردم تو ریلیز بعدی. ضمنا بچه ها ریلیز های بعدی رو توی ریپوی مرتضی ادامه میدیم. اونجا رو هم چک کنید

تروخدا این ماکس 16 رو همین امشب حلش کنید خیلی تو مخه

**Comment by goingfine** [comment]
اینم بخاطر شما
محتواش رو توی فولدر برنامه جایگزین کنید
[thread-limit.zip](https://github.com/goingfine/WinCFScan/files/10826103/thread-limit.zip)

**Comment by goingfine** [comment]
ترد بالا که بزاریداحتمال تایم اوت میره بالا. شبکه تون شلوغ میشه و ممکنه ISP‌مشکوک بشه و همچنین سرور ما رو با مشکل روبرو کنه لذا ترجیحا عدد بالا نزارید

**Comment by megasoheilsh** [comment]
البته همچنان لیمیت هستش ولی رو ۱۰۰۰ تا ، میشه این محدودیت رو بردارید؟ یا اگر نمیشه بذارید رو ۱۰ هزارتا

**Comment by goingfine** [comment]
نه برای اجرا روی کلاینت بیشتر از 64 هم نرمال نیست و ما هدفمون اجرا روی سرور نیست. ضمنا  همزمان به ازای هر ترد یک پورت روی ماشین باید باز بشه و یک کلاینت v2ray اجرا بشه که کلا بیشتر از این عدد نرمال نیست

**Comment by megasoheilsh** [comment]
> نه برای اجرا روی کلاینت بیشتر از 64 هم نرمال نیست و ما هدفمون اجرا روی سرور نیست. ضمنا همزمان به ازای هر ترد یک پورت روی ماشین باید باز بشه و یک کلاینت v2ray اجرا بشه که کلا بیشتر از این عدد نرمال نیست

اتفاقا رو سرور قرار نیست اجرا بشه ، رو کلاینته ولی خوب همین ۱۰۰۰ تا هم اوکیه چیکار کنیم دیگه محدودیتشو برنمیدارید 😂
