### ISSUE TITLE
bad UI in windows 11

### ISSUE THREAD

**Issue by MB-KING** [goingfine/WinCFScan#5]
![WinCFScan_OAGhCZH76L](https://user-images.githubusercontent.com/66483255/221179962-c1344284-5f2c-4aaa-878b-cea85b6a5ca7.png)

**Comment by megasoheilsh** [comment]
in windows 10 is ok

**Comment by raminrez** [comment]
I have the same problem with Windows 11
and I have tried to fix it with full-screen, but there are still some blind spots

**Comment by hassan1439** [comment]
i have this problem too in windows 10 pro

**Comment by hassan1439** [comment]
![bug](https://user-images.githubusercontent.com/126261474/221197951-5a6be888-9dca-4eb3-9c47-b9a3b9202d5c.png)

**Comment by goingfine** [comment]
> I have the same problem with Windows 11 and I have tried to fix it with full-screen, but there are still some blind spots

can u give me a screenshot when it is on full size

**Comment by hassan1439** [comment]
![bug 2](https://user-images.githubusercontent.com/126261474/221208391-3f6234e0-7b08-4379-a485-97b2137fa8db.png)

**Comment by goingfine** [comment]
it's strange
@hassan1439  could u tell me version of your dotnet by running this: `dotnet --list-runtimes` in command prompt

**Comment by hassan1439** [comment]
C:\Users\Hassan>dotnet --list-runtimes
Microsoft.NETCore.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by goingfine** [comment]
OK.
please replace these files in app folder and tell me that if is it fixed or not
[fix-ui.zip](https://github.com/goingfine/WinCFScan/files/10825825/fix-ui.zip)
