### ISSUE TITLE
اسکن فقط لیست ایپی

### ISSUE THREAD

**Issue by megasoheilsh** [goingfine/WinCFScan#6]
سلام لطفا امکان اسکن به صورت لیست ایپی رو هم اضافه نمایید با تشکر

**Comment by HadiIravani** [comment]
هم لیست آی پی هم سابنت های خاص اگه باشه خیلی خوب میشه، اینطوری بین ۱.۵ میلیون آی پی خیلی زمان میبره تا ای پی های با کیفیت رو پیدا کنه.

**Comment by goingfine** [comment]
> هم لیست آی پی هم سابنت های خاص اگه باشه خیلی خوب میشه، اینطوری بین ۱.۵ میلیون آی پی خیلی زمان میبره تا ای پی های با کیفیت رو پیدا کنه.
امکان انتخاب ساب نت ها توی برنامه وجود داره دیگه. ضمنا اگر لیست خیلی بزرگه میتونید فایل cf.local.iplist رو دستی ویراش کنید
