### ISSUE TITLE
Please provide .NET 6 bundled package

### ISSUE THREAD

**Issue by AliM1988** [goingfine/WinCFScan#8]
Hi
Can you provide a bundled package that includes (.NET 6)? It makes independent package, no need to download and install [Microsoft .NET 6.0 Desktop Runtime].

**Comment by goingfine** [comment]
I dont know what do u mean. u must install dot net runtime on your windows
what is your windows and dotnet? run this `dotnet --list-runtimes`

**Comment by AliM1988** [comment]
My OS version is windows 8. So .NET 6 can't be installed on it. 
Please see v2rayN which provide a bundled package that .NET 6 is embed on it. ([Link](https://github.com/2dust/v2rayN/releases/tag/6.12))
